baseurl = "http://duncombe.github.io/glossary"
languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
Title = "ocean data acronyms" 
[params]
 Description = "A glossary of data management acronyms"
 Copyright = "(C) 2014 C. M. Duncombe Rae. Copyright reserved." 

